local BrickColors = {
	'Earth green',
	'Slime green',
	'Bright bluish green',
	'Deep blue',
	'Dark blue',
	'Navy blue',
	'Parsley green',
	'Dark green',
	'Teal',
	'Steel blue',
	'Storm blue',
	'Lapis',
	'Dark indigo',
	'Camo',
	'Sea green',
	'Shamrock',
	'Toothpaste',
	'Sand blue',
	'Medium blue',
	'Bright blue',
	'Really blue',
	'Mulberry',
	'Forest green',
	'Bright green',
	'Grime',
	'Lime green',
	'Pastel blue-green',
	'Electric blue',
	'Lavender',
	'Royal purple',
	'Eggplant',
	'Sand green',
	'Moss',
	'Artichoke',
	'Sage green',
	'Pastel light blue',
	'Cadet blue',
	'Cyan',
	'Alder',
	'Lilac',
	'Plum',
	'Bright violet',
	'Olive',
	'Br. yellowish green',
	'Olivine',
	'Laurel green',
	'Pastel Blue',
	'Pastel violet',
	'Pink',
	'Hot pink',
	'Magenta',
	'Crimson',
	'Deep orange',
	'New Yeller',
	'Medium green',
	'Mint',
	'Pastel green',
	'Light blue',
	'Baby blue',
	'Carnation pink',
	'Persimmon',
	'Really red',
	'Bright red',
	'Maroon',
	'Gold',
	'Bright yellow',
	'Daisy orange',
	'Cool yellow',
	'Pastel yellow',
	'Fog',
	'Mauve',
	'Sunrise',
	'Terra Cotta',
	'Dusty Rose',
	'Cocoa',
	'Neon orange',
	'Bright orange',
	'Wheat',
	'Buttermilk',
	'Light reddish violet',
	'Pastel orange',
	'Salmon',
	'Tawny',
	'Rust',
	'CGA brown',
	'Br. yellowish orange',
	'Cashmere',
	'Khaki',
	'Seashell',
	'Pastel brown',
	'Light orange',
	'Medium red',
	'Burgundy',
	'Reddish brown',
	'Cork',
	'Burlap',
	'Beige',
	'Oyster',
	'Brick yellow',
	'Nougat',
	'Brown',
	'Pine Cone',
	'Fawn brown',
	'Sand red',
	'Hurricane grey',
	'Cloudy grey',
	'Linen',
	'Copper',
	'Dark orange',
	'Dirt brown',
	'Bronze',
	'Flint',
	'Dark taupe',
	'Burnt Sienna',
	'Really black',
	'Light stone grey',
	'Dark stone grey',
	'Medium stone grey',
	'Mid gray',
	'Quill grey',
	'Lily white',
	'Black',
	'Smoky grey',
	'Fossil',
	'Ghost grey',
	'Pearl',
	'White',
	'Institutional white'
};

return BrickColors;	